name: 'Hello World'
description: 'Greet someone and record the time'

branding:
  icon: terminal
  color: gray-dark

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    value:
    description: 'The time we greeted you'
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
